networks:
  app-network:
    driver: bridge

volumes:
  data-kafka: null

services:
  gateway:
    image: graviteeio/apim-gateway:4.5.3
    container_name: gio_apim_gateway_kafka_gateway
    restart: always
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - ./config/plugin:/opt/graviteeio-gateway/plugins-ext
      - ./config/ssl:/opt/graviteeio-gateway/kafka/ssl
      - ./config/gateway-config:/opt/graviteeio-gateway/kafka/gateway-config
    environment:
      - gravitee_plugins_path_0=/opt/graviteeio-gateway/plugins
      - gravitee_plugins_path_1=/opt/graviteeio-gateway/plugins-ext
      - gravitee_management_type=none
      - gravitee_ratelimit_type=none
      - gravitee_alerts_alert-engine_enabled=false
      - gravitee_reporters_elasticsearch_enabled=false
      - gravitee_services_kafka_gateway_enabled=true
      - gravitee_services_kafka_gateway_path=/opt/graviteeio-gateway/kafka/gateway-config/kafka-proxy-config.yml
    networks:
      - app-network

  kafka:
    image: docker.io/bitnami/kafka:3.7.1
    container_name: kafka
    volumes:
        - data-kafka:/bitnami/kafka
        - "./config/ssl/server.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
        - "./config/ssl/server.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
    ports:
        - "9091:9091"
        - "9093:9093"
        - "9094:9094"
        - "9095:9095"
        - "9096:9096"
        - "9097:9097"
    environment:
        - BITNAMI_DEBUG=true
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        #- KAFKA_KRAFT_CLUSTER_ID=kafka-cluster
        - KAFKA_KRAFT_CLUSTER_ID=OTMwNzFhYTY1ODNiNGE5OT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9093,SSL://:9094,SASL_PLAINTEXT://:9095,SASL_SSL://:9096,KAFKA_UI://:9097
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091,SSL://kafka:9094,SASL_PLAINTEXT://kafka:9095,SASL_SSL://kafka:9096,KAFKA_UI://kafka:9097
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,KAFKA_UI:PLAINTEXT,CONTROLLER:PLAINTEXT
        - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
        - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-512
        - KAFKA_NUM_PARTITIONS=1
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        # SASL settings
        - KAFKA_CLIENT_USERS=gravitee_user
        - KAFKA_CLIENT_PASSWORDS=gravitee_password
        - KAFKA_CONTROLLER_USER=controller_user
        - KAFKA_CONTROLLER_PASSWORD=controller_password
        - KAFKA_INTER_BROKER_USER=inter_broker_user
        - KAFKA_INTER_BROKER_PASSWORD=inter_broker_password
        # Certificate credentials
        - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
        - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=gravitee
        - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
        - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=gravitee
        - KAFKA_TLS_CLIENT_AUTH=requested
        - KAFKA_CERTIFICATE_PASSWORD=gravitee
        - KAFKA_TLS_TYPE=JKS
        - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    networks:
      - app-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_READONLY: "false"
      KAFKA_CLUSTERS_0_SSL_KEYSTORE_LOCATION: /certs/kafka.keystore.jks
      KAFKA_CLUSTERS_0_SSL_KEYSTORE_PASSWORD: gravitee
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_LOCATION: /certs/kafka.truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORE_PASSWORD: gravitee
      KAFKA_CLUSTERS_0_SASL_USERNAME: gravitee_user
      KAFKA_CLUSTERS_0_SASL_PASSWORD: gravitee_password
      KAFKA_CLUSTERS_0_SASL_MECHANISM: PLAIN
    volumes:
      - "./config/ssl/server.keystore.jks:/certs/kafka.keystore.jks:ro"
      - "./config/ssl/server.truststore.jks:/certs/kafka.truststore.jks:ro"
    networks:
      - app-network